import React from 'react';
import Head from 'next/head';

import {
  Box,
  Center,
  Flex,
  HStack,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
  Text,
} from '@chakra-ui/react';
import { BiLogoGithub, BiMailSend, BiLogoLinkedin, BiMoon } from 'react-icons/bi';
import {
  Icon,
  IconButton,
  Button,
  SimpleGrid,
  GridItem,
  useColorMode,
  useColorModeValue,
  MenuOptionGroup,
  MenuItemOption,
} from '@chakra-ui/react';

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  console.log(colorMode);
  const bg = useColorModeValue('red.500', 'red.200');
  const color = useColorModeValue('white', 'gray.800');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Flex
        // bg={bg}
        // color={color}
        height={'80vh'}
        flexDir='column'
        alignContent={'center'}
        justifyContent={'center'}>
        {/* Text */}
        <Text textStyle='h1'>
          I am a passionate Junior full - stack developer based in Tbilisi, Georgia, aiming on
          crafting great - looking software products. I focus on details, accessibility and writing
          maintainable code.
        </Text>

        {/* Icons */}
        <HStack mt={5}>
          <IconButton
            // size='xl'
            variant='outline'
            colorScheme='gray'
            aria-label='Done'
            fontSize='20px'
            icon={<BiMailSend />}
          />
          <IconButton
            // isRound={true}
            variant='outline'
            colorScheme='gray'
            aria-label='Done'
            fontSize='20px'
            icon={<BiLogoGithub />}
          />
          <IconButton
            // isRound={true}
            variant='outline'
            colorScheme='gray'
            aria-label='Done'
            fontSize='20px'
            icon={<BiLogoLinkedin />}
          />
          <IconButton
            // isRound={true}
            onClick={toggleColorMode}
            // size='xl'
            variant='outline'
            colorScheme='gray'
            aria-label='Done'
            fontSize='20px'
            icon={colorMode === 'light' ? <BiMoon /> : <BiLogoGithub />}
          />
        </HStack>

        {/* Works */}
        {/* <SimpleGrid columns={[1, 2, 2]} gap={6}>
          <GridItem>fsdfsf</GridItem>
          <GridItem>dfsdfd</GridItem>
          <GridItem>dfsdf</GridItem>
          <GridItem>fdsfdd</GridItem>
        </SimpleGrid> */}

        {/* <Button onClick={toggleColorMode}>Toggle {colorMode === 'light' ? 'Dark' : 'Light'}</Button> */}
      </Flex>
    </>
  );
}
